begin;

-- Equipment 2.1 is additive in PRE deploy. Existing date-based fields and
-- production RPC signatures remain available to the old application.
alter table public.equipment
  add column if not exists usage_type text not null default 'none',
  add column if not exists current_usage numeric(18,3),
  add column if not exists maintenance_interval_usage numeric(18,3),
  add column if not exists last_maintenance_usage numeric(18,3),
  add column if not exists next_maintenance_usage numeric(18,3);

alter table public.equipment
  drop constraint if exists equipment_usage_type_check,
  add constraint equipment_usage_type_check
    check (usage_type in ('none', 'hours', 'km')),
  drop constraint if exists equipment_current_usage_check,
  add constraint equipment_current_usage_check
    check (
      current_usage is null
      or (
        current_usage >= 0
        and current_usage <> 'NaN'::numeric
        and current_usage < 'Infinity'::numeric
      )
    ),
  drop constraint if exists equipment_maintenance_interval_usage_check,
  add constraint equipment_maintenance_interval_usage_check
    check (
      maintenance_interval_usage is null
      or (
        maintenance_interval_usage > 0
        and maintenance_interval_usage <> 'NaN'::numeric
        and maintenance_interval_usage < 'Infinity'::numeric
      )
    ),
  drop constraint if exists equipment_last_maintenance_usage_check,
  add constraint equipment_last_maintenance_usage_check
    check (
      last_maintenance_usage is null
      or (
        last_maintenance_usage >= 0
        and last_maintenance_usage <> 'NaN'::numeric
        and last_maintenance_usage < 'Infinity'::numeric
      )
    ),
  drop constraint if exists equipment_next_maintenance_usage_check,
  add constraint equipment_next_maintenance_usage_check
    check (
      next_maintenance_usage is null
      or (
        next_maintenance_usage >= 0
        and next_maintenance_usage <> 'NaN'::numeric
        and next_maintenance_usage < 'Infinity'::numeric
      )
    ),
  drop constraint if exists equipment_usage_schedule_check,
  add constraint equipment_usage_schedule_check
    check (
      (
        usage_type = 'none'
        and maintenance_interval_usage is null
        and last_maintenance_usage is null
        and next_maintenance_usage is null
      )
      or (
        usage_type in ('hours', 'km')
        and (
          (
            maintenance_interval_usage is null
            and last_maintenance_usage is null
            and next_maintenance_usage is null
          )
          or (
            maintenance_interval_usage is not null
            and next_maintenance_usage is not null
          )
        )
      )
    );

-- Usage facts are append-only absolute readings. Nullable equipment_id plus
-- snapshots preserve audit history if the equipment row is later deleted.
create table if not exists public.equipment_usage_logs (
  id bigint generated by default as identity primary key,
  equipment_id bigint,
  equipment_name_snapshot text not null,
  inventory_number_snapshot text,
  usage_type text not null,
  reading numeric(18,3) not null,
  previous_reading numeric(18,3),
  delta numeric(18,3) generated always as (
    case
      when previous_reading is null then null
      else reading - previous_reading
    end
  ) stored,
  reading_date date not null,
  entry_type text not null,
  note text,
  created_by uuid,
  created_by_name text not null,
  created_at timestamptz not null default clock_timestamp(),
  constraint equipment_usage_logs_equipment_fkey
    foreign key (equipment_id)
    references public.equipment(id)
    on delete set null,
  constraint equipment_usage_logs_created_by_fkey
    foreign key (created_by)
    references auth.users(id)
    on delete set null,
  constraint equipment_usage_logs_usage_type_check
    check (usage_type in ('hours', 'km')),
  constraint equipment_usage_logs_entry_type_check
    check (entry_type in ('reading', 'correction')),
  constraint equipment_usage_logs_reading_check
    check (
      reading >= 0
      and reading <> 'NaN'::numeric
      and reading < 'Infinity'::numeric
    ),
  constraint equipment_usage_logs_previous_reading_check
    check (
      previous_reading is null
      or (
        previous_reading >= 0
        and previous_reading <> 'NaN'::numeric
        and previous_reading < 'Infinity'::numeric
      )
    ),
  constraint equipment_usage_logs_snapshot_check
    check (
      char_length(btrim(equipment_name_snapshot)) between 1 and 300
      and (
        inventory_number_snapshot is null
        or char_length(btrim(inventory_number_snapshot)) between 1 and 200
      )
      and char_length(btrim(created_by_name)) between 1 and 300
    ),
  constraint equipment_usage_logs_note_check
    check (note is null or char_length(note) <= 2000)
);

create index if not exists equipment_usage_logs_equipment_date_id_idx
  on public.equipment_usage_logs (
    equipment_id,
    reading_date desc,
    id desc
  );

create index if not exists equipment_usage_due_idx
  on public.equipment (
    next_maintenance_usage,
    current_usage,
    id
  )
  where usage_type in ('hours', 'km')
    and next_maintenance_usage is not null
    and current_usage is not null;

alter table public.equipment_usage_logs enable row level security;

do $migration$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'equipment_usage_logs'
      and policyname = 'equipment_usage_logs_active_select'
  ) then
    create policy equipment_usage_logs_active_select
    on public.equipment_usage_logs
    for select
    to authenticated
    using (private.is_active_user());
  end if;
end
$migration$;

revoke all on table public.equipment_usage_logs
  from public, anon, authenticated;
grant select on table public.equipment_usage_logs
  to authenticated;

do $migration$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence(
    'public.equipment_usage_logs',
    'id'
  );

  if sequence_name is not null then
    execute format(
      'revoke all on sequence %s from public, anon, authenticated',
      sequence_name
    );
  end if;
end
$migration$;

-- Existing service rows remain valid. usage_type_snapshot makes a historical
-- reading unambiguous even if equipment settings change later.
alter table public.equipment_service_records
  add column if not exists usage_reading numeric(18,3),
  add column if not exists usage_type_snapshot text,
  add column if not exists usage_log_id bigint,
  add column if not exists created_by uuid,
  add column if not exists created_by_name text,
  add column if not exists voided_at timestamptz,
  add column if not exists voided_by uuid,
  add column if not exists void_reason text;

alter table public.equipment_service_records
  drop constraint if exists equipment_service_records_usage_snapshot_check,
  add constraint equipment_service_records_usage_snapshot_check
    check (
      (
        usage_reading is null
        and usage_type_snapshot is null
      )
      or (
        usage_reading >= 0
        and usage_reading <> 'NaN'::numeric
        and usage_reading < 'Infinity'::numeric
        and usage_type_snapshot in ('hours', 'km')
      )
    ),
  drop constraint if exists equipment_service_records_void_check,
  add constraint equipment_service_records_void_check
    check (
      (
        voided_at is null
        and voided_by is null
        and void_reason is null
      )
      or (
        voided_at is not null
        and void_reason is not null
        and char_length(btrim(void_reason)) between 1 and 1000
      )
    );

do $migration$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.equipment_service_records'::regclass
      and conname = 'equipment_service_records_usage_log_fkey'
  ) then
    alter table public.equipment_service_records
      add constraint equipment_service_records_usage_log_fkey
      foreign key (usage_log_id)
      references public.equipment_usage_logs(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.equipment_service_records'::regclass
      and conname = 'equipment_service_records_created_by_fkey'
  ) then
    alter table public.equipment_service_records
      add constraint equipment_service_records_created_by_fkey
      foreign key (created_by)
      references auth.users(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.equipment_service_records'::regclass
      and conname = 'equipment_service_records_voided_by_fkey'
  ) then
    alter table public.equipment_service_records
      add constraint equipment_service_records_voided_by_fkey
      foreign key (voided_by)
      references auth.users(id)
      on delete set null;
  end if;
end
$migration$;

create index if not exists equipment_service_records_active_equipment_date_idx
  on public.equipment_service_records (
    equipment_id,
    service_date desc,
    id desc
  )
  where voided_at is null;

-- Internal helper. Public callers cannot execute it directly. It is shared by
-- usage entry, maintenance completion and manual service RPCs so their reading
-- semantics cannot drift.
create or replace function private.append_equipment_usage_log(
  p_equipment_id bigint,
  p_reading numeric,
  p_reading_date date,
  p_entry_type text,
  p_note text,
  p_actor_id uuid,
  p_actor_name text,
  p_skip_if_unchanged boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  equipment_row public.equipment%rowtype;
  previous_reading numeric(18,3);
  latest_reading_date date;
  usage_log_id bigint;
begin
  if p_reading is null
    or p_reading < 0
    or p_reading = 'NaN'::numeric
    or p_reading >= 'Infinity'::numeric
  then
    raise exception 'Usage reading must be a finite non-negative number.'
      using errcode = '22023';
  end if;

  if p_reading_date is null then
    raise exception 'Usage reading date is required.'
      using errcode = '22007';
  end if;

  if p_reading_date > (clock_timestamp() at time zone 'Europe/Kyiv')::date then
    raise exception 'Usage reading date cannot be in the future.'
      using errcode = '22007';
  end if;

  if p_entry_type not in ('reading', 'correction') then
    raise exception 'Unsupported usage entry type.'
      using errcode = '22023';
  end if;

  if p_note is not null and char_length(p_note) > 2000 then
    raise exception 'Usage note is too long.'
      using errcode = '22001';
  end if;

  select equipment.*
  into equipment_row
  from public.equipment equipment
  where equipment.id = p_equipment_id
  for update;

  if not found then
    raise exception 'Equipment was not found.'
      using errcode = 'P0002';
  end if;

  if equipment_row.usage_type not in ('hours', 'km') then
    raise exception 'Usage tracking is not configured for this equipment.'
      using errcode = '22023';
  end if;

  previous_reading := equipment_row.current_usage;

  select logs.reading_date
  into latest_reading_date
  from public.equipment_usage_logs logs
  where logs.equipment_id = equipment_row.id
  order by logs.reading_date desc, logs.id desc
  limit 1;

  if latest_reading_date is not null and p_reading_date < latest_reading_date then
    raise exception 'Usage readings must be entered in chronological order.'
      using errcode = '22007';
  end if;

  if previous_reading is not null and p_reading = previous_reading then
    if p_skip_if_unchanged then
      return jsonb_build_object(
        'equipment_id', equipment_row.id,
        'equipment_name', equipment_row.name,
        'usage_type', equipment_row.usage_type,
        'previous_current_usage', previous_reading,
        'new_current_usage', previous_reading,
        'reading_date', p_reading_date,
        'entry_type', p_entry_type,
        'usage_log_id', null,
        'appended', false
      );
    end if;

    raise exception 'The new usage reading is unchanged.'
      using errcode = '22023';
  end if;

  if p_entry_type = 'reading'
    and previous_reading is not null
    and p_reading < previous_reading
  then
    raise exception 'A normal usage reading cannot decrease.'
      using errcode = '22023';
  end if;

  insert into public.equipment_usage_logs (
    equipment_id,
    equipment_name_snapshot,
    inventory_number_snapshot,
    usage_type,
    reading,
    previous_reading,
    reading_date,
    entry_type,
    note,
    created_by,
    created_by_name
  )
  values (
    equipment_row.id,
    equipment_row.name,
    equipment_row.inventory_number,
    equipment_row.usage_type,
    p_reading,
    previous_reading,
    p_reading_date,
    p_entry_type,
    nullif(btrim(p_note), ''),
    p_actor_id,
    p_actor_name
  )
  returning id into usage_log_id;

  update public.equipment
  set current_usage = p_reading
  where id = equipment_row.id;

  return jsonb_build_object(
    'equipment_id', equipment_row.id,
    'equipment_name', equipment_row.name,
    'usage_type', equipment_row.usage_type,
    'previous_current_usage', previous_reading,
    'new_current_usage', p_reading,
    'reading_date', p_reading_date,
    'entry_type', p_entry_type,
    'usage_log_id', usage_log_id,
    'appended', true
  );
end
$function$;

revoke all on function private.append_equipment_usage_log(
  bigint,
  numeric,
  date,
  text,
  text,
  uuid,
  text,
  boolean
) from public, anon, authenticated;

-- The same active task is used for date and usage criteria. A future date is
-- not fabricated for usage-only maintenance.
create or replace function public.sync_equipment_maintenance_task(
  p_equipment_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  equipment_row public.equipment%rowtype;
  task_row public.object_tasks%rowtype;
  today date := (clock_timestamp() at time zone 'Europe/Kyiv')::date;
  usage_due boolean := false;
  usage_schedule_active boolean := false;
  desired_due_date date;
  desired_title text;
  desired_description text;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can manage equipment maintenance.'
      using errcode = '42501';
  end if;

  select equipment.*
  into equipment_row
  from public.equipment equipment
  where equipment.id = p_equipment_id
  for update;

  if not found then
    raise exception 'Equipment was not found.'
      using errcode = 'P0002';
  end if;

  usage_schedule_active :=
    equipment_row.usage_type in ('hours', 'km')
    and equipment_row.maintenance_interval_usage is not null
    and equipment_row.next_maintenance_usage is not null
    and equipment_row.maintenance_interval_usage > 0;
  usage_due :=
    usage_schedule_active
    and equipment_row.current_usage is not null
    and equipment_row.current_usage >= equipment_row.next_maintenance_usage;

  desired_due_date := equipment_row.next_service_date;

  if usage_due
    and (
      desired_due_date is null
      or today < desired_due_date
    )
  then
    desired_due_date := today;
  end if;

  desired_title := 'Планове ТО: ' || equipment_row.name;
  desired_description :=
    case
      when usage_schedule_active and equipment_row.next_service_date is not null
        then 'Планове ТО за датою або напрацюванням — залежно від того, який критерій настане раніше.'
      when usage_schedule_active
        then 'Планове ТО за напрацюванням.'
      else 'Планове ТО за датою.'
    end;

  select tasks.*
  into task_row
  from public.object_tasks tasks
  where tasks.equipment_id = equipment_row.id
    and tasks.task_source = 'equipment_maintenance'
    and tasks.status <> 'Виконано'
  order by tasks.id
  limit 1
  for update;

  if desired_due_date is null then
    if task_row.id is null then
      return jsonb_build_object('action', 'none', 'task_id', null);
    end if;

    delete from public.object_tasks tasks
    where tasks.equipment_id = equipment_row.id
      and tasks.task_source = 'equipment_maintenance'
      and tasks.status <> 'Виконано';

    return jsonb_build_object('action', 'removed', 'task_id', task_row.id);
  end if;

  if task_row.id is null then
    insert into public.object_tasks (
      object_id,
      equipment_id,
      title,
      description,
      due_date,
      assignee,
      assigned_employee_id,
      priority,
      status,
      task_source
    )
    values (
      null,
      equipment_row.id,
      desired_title,
      desired_description,
      desired_due_date,
      equipment_row.responsible,
      equipment_row.responsible_employee_id,
      'Високий',
      'Заплановано',
      'equipment_maintenance'
    )
    returning * into task_row;

    return jsonb_build_object('action', 'created', 'task_id', task_row.id);
  end if;

  if task_row.title is not distinct from desired_title
    and task_row.description is not distinct from desired_description
    and task_row.due_date is not distinct from desired_due_date
    and task_row.assignee is not distinct from equipment_row.responsible
    and task_row.assigned_employee_id is not distinct from equipment_row.responsible_employee_id
  then
    return jsonb_build_object('action', 'none', 'task_id', task_row.id);
  end if;

  update public.object_tasks
  set
    title = desired_title,
    description = desired_description,
    due_date = desired_due_date,
    assignee = equipment_row.responsible,
    assigned_employee_id = equipment_row.responsible_employee_id
  where id = task_row.id;

  return jsonb_build_object('action', 'updated', 'task_id', task_row.id);
end
$function$;

create or replace function public.configure_equipment_usage_schedule(
  p_equipment_id bigint,
  p_usage_type text,
  p_maintenance_interval_usage numeric,
  p_next_maintenance_usage numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  equipment_row public.equipment%rowtype;
  latest_usage_type text;
  next_usage numeric(18,3);
  task_result jsonb;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can configure equipment usage.'
      using errcode = '42501';
  end if;

  if p_usage_type not in ('none', 'hours', 'km') then
    raise exception 'Unsupported equipment usage type.'
      using errcode = '22023';
  end if;

  if p_maintenance_interval_usage is not null
    and (
      p_maintenance_interval_usage <= 0
      or p_maintenance_interval_usage = 'NaN'::numeric
      or p_maintenance_interval_usage >= 'Infinity'::numeric
    )
  then
    raise exception 'Usage maintenance interval must be finite and greater than zero.'
      using errcode = '22023';
  end if;

  if p_next_maintenance_usage is not null
    and (
      p_next_maintenance_usage < 0
      or p_next_maintenance_usage = 'NaN'::numeric
      or p_next_maintenance_usage >= 'Infinity'::numeric
    )
  then
    raise exception 'Next maintenance usage must be finite and non-negative.'
      using errcode = '22023';
  end if;

  select equipment.*
  into equipment_row
  from public.equipment equipment
  where equipment.id = p_equipment_id
  for update;

  if not found then
    raise exception 'Equipment was not found.'
      using errcode = 'P0002';
  end if;

  select logs.usage_type
  into latest_usage_type
  from public.equipment_usage_logs logs
  where logs.equipment_id = equipment_row.id
  order by logs.reading_date desc, logs.id desc
  limit 1;

  if p_usage_type in ('hours', 'km')
    and latest_usage_type is not null
    and latest_usage_type <> p_usage_type
  then
    raise exception 'Existing usage history uses a different measurement type.'
      using errcode = '22023';
  end if;

  if p_usage_type = 'none' then
    update public.equipment
    set
      usage_type = 'none',
      maintenance_interval_usage = null,
      last_maintenance_usage = null,
      next_maintenance_usage = null
    where id = equipment_row.id;
  else
    if p_maintenance_interval_usage is null
      and p_next_maintenance_usage is not null
    then
      raise exception 'A next usage threshold requires a maintenance interval.'
        using errcode = '22023';
    end if;

    next_usage := p_next_maintenance_usage;

    if p_maintenance_interval_usage is not null and next_usage is null then
      if equipment_row.current_usage is null then
        raise exception 'Record the current usage before enabling usage maintenance.'
          using errcode = '22023';
      end if;

      next_usage := equipment_row.current_usage + p_maintenance_interval_usage;
    end if;

    update public.equipment
    set
      usage_type = p_usage_type,
      maintenance_interval_usage = p_maintenance_interval_usage,
      next_maintenance_usage = next_usage,
      last_maintenance_usage = case
        when p_maintenance_interval_usage is null then null
        else last_maintenance_usage
      end
    where id = equipment_row.id;
  end if;

  task_result := public.sync_equipment_maintenance_task(equipment_row.id);

  return jsonb_build_object(
    'equipment_id', equipment_row.id,
    'equipment_name', equipment_row.name,
    'previous_usage_type', equipment_row.usage_type,
    'new_usage_type', p_usage_type,
    'previous_maintenance_interval_usage', equipment_row.maintenance_interval_usage,
    'new_maintenance_interval_usage', case when p_usage_type = 'none' then null else p_maintenance_interval_usage end,
    'previous_next_maintenance_usage', equipment_row.next_maintenance_usage,
    'new_next_maintenance_usage', case when p_usage_type = 'none' then null else next_usage end,
    'task_sync', task_result
  );
end
$function$;

create or replace function public.record_equipment_usage(
  p_equipment_id bigint,
  p_reading numeric,
  p_reading_date date,
  p_entry_type text,
  p_note text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_name text;
  usage_result jsonb;
  task_result jsonb;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can record equipment usage.'
      using errcode = '42501';
  end if;

  select coalesce(
    nullif(btrim(profile.full_name), ''),
    nullif(btrim(profile.email), ''),
    'Користувач ViCourt'
  )
  into actor_name
  from public.profiles profile
  where profile.id = auth.uid();

  actor_name := coalesce(actor_name, 'Користувач ViCourt');

  usage_result := private.append_equipment_usage_log(
    p_equipment_id,
    p_reading,
    p_reading_date,
    p_entry_type,
    p_note,
    auth.uid(),
    actor_name,
    false
  );
  task_result := public.sync_equipment_maintenance_task(p_equipment_id);

  return usage_result || jsonb_build_object('task_sync', task_result);
end
$function$;

-- Fixed-arity canonical completion implementation. It owns all date/usage,
-- history and task changes in one database transaction.
create or replace function public.complete_equipment_maintenance_v2(
  p_equipment_id bigint,
  p_task_id bigint,
  p_cost numeric,
  p_performed_by text,
  p_description text,
  p_usage_reading numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  equipment_row public.equipment%rowtype;
  actor_name text;
  today date := (clock_timestamp() at time zone 'Europe/Kyiv')::date;
  has_date_schedule boolean;
  has_usage_schedule boolean;
  old_last_date date;
  old_next_date date;
  old_current_usage numeric(18,3);
  old_last_usage numeric(18,3);
  old_next_usage numeric(18,3);
  new_last_date date;
  new_next_date date;
  new_last_usage numeric(18,3);
  new_next_usage numeric(18,3);
  usage_result jsonb;
  usage_log_id bigint;
  service_history_id bigint;
  completed_task_id bigint;
  task_result jsonb;
  next_task_id bigint;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can complete equipment maintenance.'
      using errcode = '42501';
  end if;

  if p_cost is null
    or p_cost < 0
    or p_cost = 'NaN'::numeric
    or p_cost >= 'Infinity'::numeric
  then
    raise exception 'Maintenance cost must be a finite non-negative number.'
      using errcode = '22023';
  end if;

  if p_performed_by is not null and char_length(p_performed_by) > 300 then
    raise exception 'Maintenance performer is too long.'
      using errcode = '22001';
  end if;

  if p_description is not null and char_length(p_description) > 4000 then
    raise exception 'Maintenance description is too long.'
      using errcode = '22001';
  end if;

  select equipment.*
  into equipment_row
  from public.equipment equipment
  where equipment.id = p_equipment_id
  for update;

  if not found then
    raise exception 'Equipment was not found.'
      using errcode = 'P0002';
  end if;

  select coalesce(
    nullif(btrim(profile.full_name), ''),
    nullif(btrim(profile.email), ''),
    'Користувач ViCourt'
  )
  into actor_name
  from public.profiles profile
  where profile.id = auth.uid();

  actor_name := coalesce(actor_name, 'Користувач ViCourt');
  old_last_date := equipment_row.last_maintenance_date;
  old_next_date := equipment_row.next_service_date;
  old_current_usage := equipment_row.current_usage;
  old_last_usage := equipment_row.last_maintenance_usage;
  old_next_usage := equipment_row.next_maintenance_usage;

  if p_usage_reading is not null then
    usage_result := private.append_equipment_usage_log(
      equipment_row.id,
      p_usage_reading,
      today,
      'reading',
      'Показник зафіксовано під час планового ТО.',
      auth.uid(),
      actor_name,
      true
    );
    usage_log_id := (usage_result ->> 'usage_log_id')::bigint;

    select equipment.*
    into equipment_row
    from public.equipment equipment
    where equipment.id = p_equipment_id
    for update;
  end if;

  has_date_schedule :=
    equipment_row.maintenance_interval_days is not null
    and equipment_row.maintenance_interval_days > 0;
  has_usage_schedule :=
    equipment_row.usage_type in ('hours', 'km')
    and equipment_row.maintenance_interval_usage is not null
    and equipment_row.maintenance_interval_usage > 0;

  if not has_date_schedule and not has_usage_schedule then
    raise exception 'No maintenance interval is configured.'
      using errcode = '22023';
  end if;

  if has_usage_schedule and equipment_row.current_usage is null then
    raise exception 'Current usage is required to complete usage-based maintenance.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from public.equipment_service_records records
    where records.equipment_id = equipment_row.id
      and records.service_type = 'Планове обслуговування'
      and records.service_date = today
      and records.voided_at is null
  ) then
    raise exception 'Maintenance was already completed today.'
      using errcode = '23505';
  end if;

  new_last_date := case when has_date_schedule then today else old_last_date end;
  new_next_date := case
    when has_date_schedule
      then today + equipment_row.maintenance_interval_days
    else old_next_date
  end;
  new_last_usage := case
    when has_usage_schedule then equipment_row.current_usage
    else old_last_usage
  end;
  new_next_usage := case
    when has_usage_schedule
      then equipment_row.current_usage + equipment_row.maintenance_interval_usage
    else old_next_usage
  end;

  update public.equipment
  set
    last_maintenance_date = new_last_date,
    next_service_date = new_next_date,
    last_maintenance_usage = new_last_usage,
    next_maintenance_usage = new_next_usage
  where id = equipment_row.id;

  if p_task_id is not null then
    select tasks.id
    into completed_task_id
    from public.object_tasks tasks
    where tasks.id = p_task_id
      and tasks.equipment_id = equipment_row.id
      and tasks.task_source = 'equipment_maintenance'
      and tasks.status <> 'Виконано'
    for update;

    if completed_task_id is null then
      raise exception 'Active equipment maintenance task was not found.'
        using errcode = 'P0002';
    end if;
  else
    select tasks.id
    into completed_task_id
    from public.object_tasks tasks
    where tasks.equipment_id = equipment_row.id
      and tasks.task_source = 'equipment_maintenance'
      and tasks.status <> 'Виконано'
    order by tasks.id
    limit 1
    for update;
  end if;

  if completed_task_id is not null then
    update public.object_tasks
    set status = 'Виконано'
    where id = completed_task_id;
  end if;

  insert into public.equipment_service_records (
    equipment_id,
    service_type,
    service_date,
    cost,
    performed_by,
    description,
    next_service_date,
    usage_reading,
    usage_type_snapshot,
    usage_log_id,
    created_by,
    created_by_name
  )
  values (
    equipment_row.id,
    'Планове обслуговування',
    today,
    p_cost,
    coalesce(nullif(btrim(p_performed_by), ''), actor_name),
    nullif(btrim(p_description), ''),
    new_next_date,
    case
      when has_usage_schedule or p_usage_reading is not null
        then equipment_row.current_usage
      else null
    end,
    case
      when has_usage_schedule or p_usage_reading is not null
        then equipment_row.usage_type
      else null
    end,
    usage_log_id,
    auth.uid(),
    actor_name
  )
  returning id into service_history_id;

  task_result := public.sync_equipment_maintenance_task(equipment_row.id);
  next_task_id := (task_result ->> 'task_id')::bigint;

  return jsonb_build_object(
    'service_history_id', service_history_id,
    'equipment_name', equipment_row.name,
    'previous_last_maintenance_date', old_last_date,
    'new_last_maintenance_date', new_last_date,
    'previous_next_service_date', old_next_date,
    'new_next_service_date', new_next_date,
    'maintenance_interval_days', equipment_row.maintenance_interval_days,
    'usage_type', equipment_row.usage_type,
    'previous_current_usage', old_current_usage,
    'new_current_usage', equipment_row.current_usage,
    'previous_last_maintenance_usage', old_last_usage,
    'new_last_maintenance_usage', new_last_usage,
    'previous_next_maintenance_usage', old_next_usage,
    'new_next_maintenance_usage', new_next_usage,
    'maintenance_interval_usage', equipment_row.maintenance_interval_usage,
    'usage_log_id', usage_log_id,
    'completed_task_id', completed_task_id,
    'next_task_id', next_task_id
  );
end
$function$;

-- Current five-argument production contract: no defaults.
create or replace function public.complete_equipment_maintenance(
  p_equipment_id bigint,
  p_task_id bigint,
  p_cost numeric,
  p_performed_by text,
  p_description text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
begin
  return public.complete_equipment_maintenance_v2(
    p_equipment_id,
    p_task_id,
    p_cost,
    p_performed_by,
    p_description,
    null
  );
end
$function$;

-- Legacy four-argument production contract. Keep all confirmed defaults.
create or replace function public.complete_equipment_maintenance(
  p_equipment_id bigint,
  p_cost numeric default 0,
  p_performed_by text default null::text,
  p_description text default null::text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
begin
  return public.complete_equipment_maintenance(
    p_equipment_id,
    null::bigint,
    p_cost,
    p_performed_by,
    p_description
  );
end
$function$;

create or replace function public.create_equipment_service_record_v2(
  p_equipment_id bigint,
  p_service_type text,
  p_service_date date,
  p_cost numeric,
  p_performed_by text,
  p_description text,
  p_next_service_date date,
  p_usage_reading numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  equipment_row public.equipment%rowtype;
  actor_name text;
  usage_result jsonb;
  usage_log_id bigint;
  service_history_id bigint;
  task_result jsonb;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can create equipment service records.'
      using errcode = '42501';
  end if;

  if p_service_type not in (
    'Планове обслуговування',
    'Ремонт',
    'Заміна запчастин',
    'Діагностика',
    'Інше'
  ) then
    raise exception 'Unsupported equipment service type.'
      using errcode = '22023';
  end if;

  if p_service_type = 'Планове обслуговування' then
    raise exception 'Use the canonical maintenance completion function for planned maintenance.'
      using errcode = '22023';
  end if;

  if p_service_date is null
    or p_service_date > (clock_timestamp() at time zone 'Europe/Kyiv')::date
  then
    raise exception 'Service date is invalid or in the future.'
      using errcode = '22007';
  end if;

  if p_next_service_date is not null and p_next_service_date < p_service_date then
    raise exception 'Next service date cannot be before the service date.'
      using errcode = '22007';
  end if;

  if p_cost is null
    or p_cost < 0
    or p_cost = 'NaN'::numeric
    or p_cost >= 'Infinity'::numeric
  then
    raise exception 'Service cost must be a finite non-negative number.'
      using errcode = '22023';
  end if;

  if p_performed_by is not null and char_length(p_performed_by) > 300 then
    raise exception 'Service performer is too long.'
      using errcode = '22001';
  end if;

  if p_description is not null and char_length(p_description) > 4000 then
    raise exception 'Service description is too long.'
      using errcode = '22001';
  end if;

  select equipment.*
  into equipment_row
  from public.equipment equipment
  where equipment.id = p_equipment_id
  for update;

  if not found then
    raise exception 'Equipment was not found.'
      using errcode = 'P0002';
  end if;

  select coalesce(
    nullif(btrim(profile.full_name), ''),
    nullif(btrim(profile.email), ''),
    'Користувач ViCourt'
  )
  into actor_name
  from public.profiles profile
  where profile.id = auth.uid();

  actor_name := coalesce(actor_name, 'Користувач ViCourt');

  if p_usage_reading is not null then
    usage_result := private.append_equipment_usage_log(
      equipment_row.id,
      p_usage_reading,
      p_service_date,
      'reading',
      'Показник зафіксовано разом із сервісним записом.',
      auth.uid(),
      actor_name,
      true
    );
    usage_log_id := (usage_result ->> 'usage_log_id')::bigint;

    select equipment.*
    into equipment_row
    from public.equipment equipment
    where equipment.id = p_equipment_id
    for update;
  end if;

  insert into public.equipment_service_records (
    equipment_id,
    service_type,
    service_date,
    cost,
    performed_by,
    description,
    next_service_date,
    usage_reading,
    usage_type_snapshot,
    usage_log_id,
    created_by,
    created_by_name
  )
  values (
    equipment_row.id,
    p_service_type,
    p_service_date,
    p_cost,
    nullif(btrim(p_performed_by), ''),
    nullif(btrim(p_description), ''),
    p_next_service_date,
    case when p_usage_reading is not null then equipment_row.current_usage else null end,
    case when p_usage_reading is not null then equipment_row.usage_type else null end,
    usage_log_id,
    auth.uid(),
    actor_name
  )
  returning id into service_history_id;

  if p_next_service_date is not null then
    update public.equipment
    set next_service_date = p_next_service_date
    where id = equipment_row.id;
  end if;

  task_result := public.sync_equipment_maintenance_task(equipment_row.id);

  return jsonb_build_object(
    'service_history_id', service_history_id,
    'equipment_id', equipment_row.id,
    'equipment_name', equipment_row.name,
    'service_type', p_service_type,
    'service_date', p_service_date,
    'cost', p_cost,
    'performed_by', nullif(btrim(p_performed_by), ''),
    'description', nullif(btrim(p_description), ''),
    'next_service_date', p_next_service_date,
    'usage_type', case when p_usage_reading is not null then equipment_row.usage_type else null end,
    'usage_reading', case when p_usage_reading is not null then equipment_row.current_usage else null end,
    'usage_log_id', usage_log_id,
    'task_sync', task_result
  );
end
$function$;

create or replace function public.void_equipment_service_record(
  p_service_record_id bigint,
  p_void_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  service_row public.equipment_service_records%rowtype;
  equipment_name text;
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.is_admin()
  then
    raise exception 'Only an active administrator can void equipment service records.'
      using errcode = '42501';
  end if;

  if p_void_reason is null
    or char_length(btrim(p_void_reason)) not between 1 and 1000
  then
    raise exception 'A void reason is required.'
      using errcode = '22023';
  end if;

  select records.*
  into service_row
  from public.equipment_service_records records
  where records.id = p_service_record_id
  for update;

  if not found then
    raise exception 'Equipment service record was not found.'
      using errcode = 'P0002';
  end if;

  if service_row.voided_at is not null then
    raise exception 'Equipment service record is already voided.'
      using errcode = '22023';
  end if;

  select equipment.name
  into equipment_name
  from public.equipment equipment
  where equipment.id = service_row.equipment_id;

  update public.equipment_service_records
  set
    voided_at = clock_timestamp(),
    voided_by = auth.uid(),
    void_reason = btrim(p_void_reason)
  where id = service_row.id;

  return jsonb_build_object(
    'service_history_id', service_row.id,
    'equipment_id', service_row.equipment_id,
    'equipment_name', coalesce(equipment_name, 'Техніку видалено'),
    'service_type', service_row.service_type,
    'service_date', service_row.service_date,
    'cost', service_row.cost,
    'void_reason', btrim(p_void_reason)
  );
end
$function$;

revoke all on function public.sync_equipment_maintenance_task(bigint)
  from public, anon, authenticated;
grant execute on function public.sync_equipment_maintenance_task(bigint)
  to authenticated;

revoke all on function public.configure_equipment_usage_schedule(
  bigint,
  text,
  numeric,
  numeric
) from public, anon, authenticated;
grant execute on function public.configure_equipment_usage_schedule(
  bigint,
  text,
  numeric,
  numeric
) to authenticated;

revoke all on function public.record_equipment_usage(
  bigint,
  numeric,
  date,
  text,
  text
) from public, anon, authenticated;
grant execute on function public.record_equipment_usage(
  bigint,
  numeric,
  date,
  text,
  text
) to authenticated;

revoke all on function public.complete_equipment_maintenance_v2(
  bigint,
  bigint,
  numeric,
  text,
  text,
  numeric
) from public, anon, authenticated;
grant execute on function public.complete_equipment_maintenance_v2(
  bigint,
  bigint,
  numeric,
  text,
  text,
  numeric
) to authenticated;

revoke all on function public.complete_equipment_maintenance(
  bigint,
  bigint,
  numeric,
  text,
  text
) from public, anon, authenticated;
grant execute on function public.complete_equipment_maintenance(
  bigint,
  bigint,
  numeric,
  text,
  text
) to authenticated;

revoke all on function public.complete_equipment_maintenance(
  bigint,
  numeric,
  text,
  text
) from public, anon, authenticated;
grant execute on function public.complete_equipment_maintenance(
  bigint,
  numeric,
  text,
  text
) to authenticated;

revoke all on function public.create_equipment_service_record_v2(
  bigint,
  text,
  date,
  numeric,
  text,
  text,
  date,
  numeric
) from public, anon, authenticated;
grant execute on function public.create_equipment_service_record_v2(
  bigint,
  text,
  date,
  numeric,
  text,
  text,
  date,
  numeric
) to authenticated;

revoke all on function public.void_equipment_service_record(bigint, text)
  from public, anon, authenticated;
grant execute on function public.void_equipment_service_record(bigint, text)
  to authenticated;

notify pgrst, 'reload schema';

commit;
