begin;

-- Tasks 2.1 PRE is additive. It can be applied while the previous Vercel
-- deployment is still serving requests. Do not create active recurring series
-- until the Tasks 2.1 application and the POST guard are deployed.
create table if not exists public.task_templates (
  id bigint generated by default as identity primary key,
  source_template_id bigint,
  title text not null,
  description text,
  target_type text not null,
  object_id bigint,
  equipment_id bigint,
  priority text not null default 'Середній',
  assigned_employee_id bigint,
  assignee text,
  recurrence_type text not null default 'none',
  recurrence_interval integer,
  anchor_due_date date,
  is_active boolean not null default false,
  created_by uuid,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint task_templates_source_template_fkey
    foreign key (source_template_id)
    references public.task_templates(id)
    on delete set null,
  constraint task_templates_object_fkey
    foreign key (object_id)
    references public.objects(id)
    on delete set null,
  constraint task_templates_equipment_fkey
    foreign key (equipment_id)
    references public.equipment(id)
    on delete set null,
  constraint task_templates_employee_fkey
    foreign key (assigned_employee_id)
    references public.employees(id)
    on delete set null,
  constraint task_templates_created_by_fkey
    foreign key (created_by)
    references auth.users(id)
    on delete set null,
  constraint task_templates_title_check
    check (char_length(btrim(title)) between 1 and 300),
  constraint task_templates_description_check
    check (description is null or char_length(description) <= 4000),
  constraint task_templates_target_type_check
    check (target_type in ('object', 'equipment')),
  constraint task_templates_target_shape_check
    check (
      (target_type = 'object' and equipment_id is null)
      or (target_type = 'equipment' and object_id is null)
    ),
  constraint task_templates_priority_check
    check (priority in ('Низький', 'Середній', 'Високий', 'Терміновий')),
  constraint task_templates_recurrence_type_check
    check (recurrence_type in ('none', 'daily', 'weekly', 'monthly', 'custom')),
  constraint task_templates_recurrence_interval_check
    check (
      (recurrence_type = 'none' and recurrence_interval is null)
      or (
        recurrence_type in ('daily', 'weekly', 'monthly')
        and recurrence_interval = 1
      )
      or (
        recurrence_type = 'custom'
        and recurrence_interval > 0
      )
    ),
  constraint task_templates_active_series_check
    check (
      not is_active
      or (
        recurrence_type <> 'none'
        and anchor_due_date is not null
        and (
          (target_type = 'object' and object_id is not null and equipment_id is null)
          or (
            target_type = 'equipment'
            and equipment_id is not null
            and object_id is null
          )
        )
      )
    ),
  constraint task_templates_assignee_check
    check (assignee is null or char_length(btrim(assignee)) between 1 and 300)
);

create index if not exists task_templates_updated_id_idx
  on public.task_templates (updated_at desc, id desc);

create index if not exists task_templates_object_idx
  on public.task_templates (object_id, is_active, id)
  where object_id is not null;

create index if not exists task_templates_equipment_idx
  on public.task_templates (equipment_id, is_active, id)
  where equipment_id is not null;

-- A double click on "create series from blueprint" reuses the active copy.
create unique index if not exists task_templates_active_source_object_uidx
  on public.task_templates (source_template_id, object_id)
  where is_active
    and source_template_id is not null
    and target_type = 'object'
    and object_id is not null;

create unique index if not exists task_templates_active_source_equipment_uidx
  on public.task_templates (source_template_id, equipment_id)
  where is_active
    and source_template_id is not null
    and target_type = 'equipment'
    and equipment_id is not null;

alter table public.object_tasks
  add column if not exists task_template_id bigint,
  add column if not exists recurrence_sequence bigint;

do $migration$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.object_tasks'::regclass
      and conname = 'object_tasks_task_template_fkey'
  ) then
    alter table public.object_tasks
      add constraint object_tasks_task_template_fkey
      foreign key (task_template_id)
      references public.task_templates(id)
      on delete restrict;
  end if;
end
$migration$;

alter table public.object_tasks
  drop constraint if exists object_tasks_recurrence_link_check,
  add constraint object_tasks_recurrence_link_check
    check (
      (
        task_template_id is null
        and recurrence_sequence is null
      )
      or (
        task_template_id is not null
        and recurrence_sequence is not null
        and recurrence_sequence > 0
        and task_source = 'manual'
      )
    );

create unique index if not exists object_tasks_template_sequence_uidx
  on public.object_tasks (task_template_id, recurrence_sequence)
  where task_template_id is not null;

-- At most one unfinished occurrence exists for one recurring series. Historical
-- completed occurrences remain separate rows.
create unique index if not exists object_tasks_template_active_uidx
  on public.object_tasks (task_template_id)
  where task_template_id is not null
    and status <> 'Виконано';

create or replace function private.touch_task_template_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  new.updated_at := clock_timestamp();
  return new;
end
$function$;

revoke all on function private.touch_task_template_updated_at()
  from public, anon, authenticated;

drop trigger if exists task_templates_touch_updated_at
  on public.task_templates;

create trigger task_templates_touch_updated_at
before update on public.task_templates
for each row
execute function private.touch_task_template_updated_at();

-- ON DELETE SET NULL must not leave an active series without its target.
create or replace function private.disable_task_template_without_target()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if new.is_active
    and (
      (new.target_type = 'object' and new.object_id is null)
      or (new.target_type = 'equipment' and new.equipment_id is null)
    )
  then
    new.is_active := false;
  end if;

  return new;
end
$function$;

revoke all on function private.disable_task_template_without_target()
  from public, anon, authenticated;

drop trigger if exists task_templates_disable_missing_target
  on public.task_templates;

create trigger task_templates_disable_missing_target
before update of object_id, equipment_id on public.task_templates
for each row
execute function private.disable_task_template_without_target();

alter table public.task_templates enable row level security;

drop policy if exists task_templates_management_select
  on public.task_templates;

create policy task_templates_management_select
on public.task_templates
for select
to authenticated
using (
  private.is_active_user()
  and private.has_role(
    array['admin', 'object_manager']::text[]
  )
);

revoke all on table public.task_templates
  from public, anon, authenticated;
grant select on table public.task_templates
  to authenticated;

do $migration$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence(
    'public.task_templates',
    'id'
  );

  if sequence_name is not null then
    execute format(
      'revoke all on sequence %s from public, anon, authenticated',
      sequence_name
    );
  end if;
end
$migration$;

create or replace function private.assert_task_template_management()
returns void
language plpgsql
stable
security invoker
set search_path = ''
as $function$
begin
  if auth.uid() is null
    or not private.is_active_user()
    or not private.has_role(
      array['admin', 'object_manager']::text[]
    )
  then
    raise exception 'Only an active administrator or object manager can manage task templates.'
      using errcode = '42501';
  end if;
end
$function$;

revoke all on function private.assert_task_template_management()
  from public, anon, authenticated;

create or replace function private.resolve_task_assignee_name(
  p_employee_id bigint
)
returns text
language sql
stable
security definer
set search_path = ''
as $function$
  select nullif(
    btrim(
      concat_ws(
        ' ',
        employee.last_name,
        employee.first_name
      )
    ),
    ''
  )
  from public.employees employee
  where employee.id = p_employee_id
$function$;

revoke all on function private.resolve_task_assignee_name(bigint)
  from public, anon, authenticated;

create or replace function private.task_recurrence_due_date(
  p_anchor_due_date date,
  p_recurrence_type text,
  p_recurrence_interval integer,
  p_sequence bigint
)
returns date
language plpgsql
immutable
security invoker
set search_path = ''
as $function$
declare
  month_start date;
  target_month date;
  target_day integer;
  day_step integer;
begin
  if p_anchor_due_date is null
    or p_sequence is null
    or p_sequence <= 0
  then
    raise exception 'Invalid recurrence anchor or sequence.'
      using errcode = '22023';
  end if;

  if p_recurrence_type = 'daily' then
    day_step := 1;
  elsif p_recurrence_type = 'weekly' then
    day_step := 7;
  elsif p_recurrence_type = 'custom'
    and p_recurrence_interval is not null
    and p_recurrence_interval > 0
  then
    day_step := p_recurrence_interval;
  elsif p_recurrence_type = 'monthly' then
    if p_sequence > 2147483647 then
      raise exception 'Recurrence sequence is too large.'
        using errcode = '22003';
    end if;

    month_start := date_trunc('month', p_anchor_due_date)::date;
    target_month := (
      month_start
      + make_interval(months => (p_sequence - 1)::integer)
    )::date;
    target_day := least(
      extract(day from p_anchor_due_date)::integer,
      extract(
        day from (
          target_month
          + interval '1 month'
          - interval '1 day'
        )
      )::integer
    );

    return target_month + (target_day - 1);
  else
    raise exception 'Unsupported recurrence configuration.'
      using errcode = '22023';
  end if;

  if (p_sequence - 1) > (2147483647 / day_step) then
    raise exception 'Recurrence sequence is too large.'
      using errcode = '22003';
  end if;

  return p_anchor_due_date
    + (((p_sequence - 1) * day_step)::integer);
end
$function$;

revoke all on function private.task_recurrence_due_date(
  date,
  text,
  integer,
  bigint
) from public, anon, authenticated;

-- Sequence 1 is the anchor slot. The returned slot is always strictly after
-- p_after_date and never drifts from the original anchor.
create or replace function private.next_task_recurrence_slot(
  p_anchor_due_date date,
  p_recurrence_type text,
  p_recurrence_interval integer,
  p_current_sequence bigint,
  p_after_date date
)
returns table (
  recurrence_sequence bigint,
  due_date date
)
language plpgsql
immutable
security invoker
set search_path = ''
as $function$
declare
  candidate_sequence bigint;
  candidate_due_date date;
  day_step integer;
  months_difference integer;
  attempts integer := 0;
begin
  if p_anchor_due_date is null
    or p_after_date is null
    or p_current_sequence is null
    or p_current_sequence < 0
  then
    raise exception 'Invalid recurrence slot input.'
      using errcode = '22023';
  end if;

  if p_recurrence_type = 'daily' then
    day_step := 1;
  elsif p_recurrence_type = 'weekly' then
    day_step := 7;
  elsif p_recurrence_type = 'custom'
    and p_recurrence_interval is not null
    and p_recurrence_interval > 0
  then
    day_step := p_recurrence_interval;
  end if;

  if day_step is not null then
    candidate_sequence := greatest(
      p_current_sequence + 1,
      case
        when p_after_date < p_anchor_due_date then 1
        else ((p_after_date - p_anchor_due_date) / day_step)::bigint + 2
      end
    );
  elsif p_recurrence_type = 'monthly' then
    months_difference :=
      (
        extract(year from p_after_date)::integer
        - extract(year from p_anchor_due_date)::integer
      ) * 12
      + extract(month from p_after_date)::integer
      - extract(month from p_anchor_due_date)::integer;
    candidate_sequence := greatest(
      p_current_sequence + 1,
      months_difference::bigint + 1,
      1
    );
  else
    raise exception 'Unsupported recurrence configuration.'
      using errcode = '22023';
  end if;

  loop
    attempts := attempts + 1;
    if attempts > 100000 then
      raise exception 'Unable to calculate the next recurrence slot.'
        using errcode = '54000';
    end if;

    candidate_due_date := private.task_recurrence_due_date(
      p_anchor_due_date,
      p_recurrence_type,
      p_recurrence_interval,
      candidate_sequence
    );

    if candidate_due_date > p_after_date then
      return query
      select candidate_sequence, candidate_due_date;
      return;
    end if;

    candidate_sequence := candidate_sequence + 1;
  end loop;
end
$function$;

revoke all on function private.next_task_recurrence_slot(
  date,
  text,
  integer,
  bigint,
  date
) from public, anon, authenticated;

create or replace function private.create_task_template_occurrence(
  p_template_id bigint,
  p_sequence bigint,
  p_due_date date
)
returns public.object_tasks
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
begin
  perform pg_catalog.set_config(
    'vicourt.recurring_task_mutation',
    'on',
    true
  );

  select template.*
  into template_row
  from public.task_templates template
  where template.id = p_template_id;

  if not found then
    raise exception 'Task template was not found.'
      using errcode = 'P0002';
  end if;

  if not template_row.is_active
    or template_row.recurrence_type = 'none'
    or template_row.anchor_due_date is null
    or p_sequence is null
    or p_sequence <= 0
    or p_due_date is null
  then
    raise exception 'Task template is not an active recurring series.'
      using errcode = '22023';
  end if;

  insert into public.object_tasks (
    object_id,
    equipment_id,
    title,
    description,
    due_date,
    assignee,
    assigned_employee_id,
    priority,
    status,
    task_source,
    task_template_id,
    recurrence_sequence
  )
  values (
    template_row.object_id,
    template_row.equipment_id,
    template_row.title,
    template_row.description,
    p_due_date,
    template_row.assignee,
    template_row.assigned_employee_id,
    template_row.priority,
    'Заплановано',
    'manual',
    template_row.id,
    p_sequence
  )
  on conflict do nothing
  returning * into task_row;

  if task_row.id is null then
    select task.*
    into task_row
    from public.object_tasks task
    where task.task_template_id = template_row.id
      and (
        task.recurrence_sequence = p_sequence
        or task.status <> 'Виконано'
      )
    order by
      (task.recurrence_sequence = p_sequence) desc,
      task.recurrence_sequence desc,
      task.id desc
    limit 1;
  end if;

  if task_row.id is null then
    raise exception 'Unable to create or resolve recurring task occurrence.';
  end if;

  return task_row;
end
$function$;

revoke all on function private.create_task_template_occurrence(
  bigint,
  bigint,
  date
) from public, anon, authenticated;

create or replace function public.create_task_template(
  p_title text,
  p_description text,
  p_target_type text,
  p_object_id bigint,
  p_equipment_id bigint,
  p_priority text,
  p_assigned_employee_id bigint,
  p_recurrence_type text,
  p_recurrence_interval integer,
  p_anchor_due_date date,
  p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
  first_slot record;
  assignee_name text;
  today date := (clock_timestamp() at time zone 'Europe/Kyiv')::date;
begin
  perform private.assert_task_template_management();

  if p_title is null
    or char_length(btrim(p_title)) not between 1 and 300
    or (p_description is not null and char_length(p_description) > 4000)
    or p_target_type not in ('object', 'equipment')
    or p_priority not in ('Низький', 'Середній', 'Високий', 'Терміновий')
    or p_recurrence_type not in ('none', 'daily', 'weekly', 'monthly', 'custom')
    or p_is_active is null
  then
    raise exception 'Invalid task template values.'
      using errcode = '22023';
  end if;

  if (p_target_type = 'object' and p_equipment_id is not null)
    or (p_target_type = 'equipment' and p_object_id is not null)
    or (
      p_is_active
      and (
        (p_target_type = 'object' and p_object_id is null)
        or (p_target_type = 'equipment' and p_equipment_id is null)
      )
    )
  then
    raise exception 'A recurring series must have exactly one matching target.'
      using errcode = '22023';
  end if;

  if (p_recurrence_type = 'none' and p_recurrence_interval is not null)
    or (
      p_recurrence_type in ('daily', 'weekly', 'monthly')
      and p_recurrence_interval is distinct from 1
    )
    or (
      p_recurrence_type = 'custom'
      and (p_recurrence_interval is null or p_recurrence_interval <= 0)
    )
    or (
      p_is_active
      and (p_recurrence_type = 'none' or p_anchor_due_date is null)
    )
  then
    raise exception 'Invalid task recurrence configuration.'
      using errcode = '22023';
  end if;

  if p_object_id is not null
    and not exists (
      select 1 from public.objects object where object.id = p_object_id
    )
  then
    raise exception 'Task target object was not found.'
      using errcode = 'P0002';
  end if;

  if p_equipment_id is not null
    and not exists (
      select 1 from public.equipment equipment where equipment.id = p_equipment_id
    )
  then
    raise exception 'Task target equipment was not found.'
      using errcode = 'P0002';
  end if;

  if p_assigned_employee_id is not null then
    assignee_name := private.resolve_task_assignee_name(
      p_assigned_employee_id
    );
    if assignee_name is null then
      raise exception 'Assigned employee was not found.'
        using errcode = 'P0002';
    end if;
  end if;

  insert into public.task_templates (
    title,
    description,
    target_type,
    object_id,
    equipment_id,
    priority,
    assigned_employee_id,
    assignee,
    recurrence_type,
    recurrence_interval,
    anchor_due_date,
    is_active,
    created_by
  )
  values (
    btrim(p_title),
    nullif(btrim(p_description), ''),
    p_target_type,
    p_object_id,
    p_equipment_id,
    p_priority,
    p_assigned_employee_id,
    assignee_name,
    p_recurrence_type,
    p_recurrence_interval,
    p_anchor_due_date,
    p_is_active,
    auth.uid()
  )
  returning * into template_row;

  if template_row.is_active then
    select *
    into first_slot
    from private.next_task_recurrence_slot(
      template_row.anchor_due_date,
      template_row.recurrence_type,
      template_row.recurrence_interval,
      0,
      today - 1
    );

    task_row := private.create_task_template_occurrence(
      template_row.id,
      first_slot.recurrence_sequence,
      first_slot.due_date
    );
  end if;

  return jsonb_build_object(
    'template', to_jsonb(template_row),
    'first_task', case when task_row.id is null then null else to_jsonb(task_row) end,
    'reused_existing_series', false
  );
end
$function$;

create or replace function public.update_task_template(
  p_template_id bigint,
  p_title text,
  p_description text,
  p_priority text,
  p_assigned_employee_id bigint,
  p_recurrence_type text,
  p_recurrence_interval integer,
  p_anchor_due_date date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
  assignee_name text;
  recalculated_due_date date;
begin
  perform private.assert_task_template_management();

  select template.*
  into template_row
  from public.task_templates template
  where template.id = p_template_id
  for update;

  if not found then
    raise exception 'Task template was not found.'
      using errcode = 'P0002';
  end if;

  if p_title is null
    or char_length(btrim(p_title)) not between 1 and 300
    or (p_description is not null and char_length(p_description) > 4000)
    or p_priority not in ('Низький', 'Середній', 'Високий', 'Терміновий')
    or p_recurrence_type not in ('none', 'daily', 'weekly', 'monthly', 'custom')
    or (p_recurrence_type = 'none' and p_recurrence_interval is not null)
    or (
      p_recurrence_type in ('daily', 'weekly', 'monthly')
      and p_recurrence_interval is distinct from 1
    )
    or (
      p_recurrence_type = 'custom'
      and (p_recurrence_interval is null or p_recurrence_interval <= 0)
    )
    or (
      template_row.is_active
      and (p_recurrence_type = 'none' or p_anchor_due_date is null)
    )
  then
    raise exception 'Invalid task template values.'
      using errcode = '22023';
  end if;

  if p_assigned_employee_id is not null then
    assignee_name := private.resolve_task_assignee_name(
      p_assigned_employee_id
    );
    if assignee_name is null then
      raise exception 'Assigned employee was not found.'
        using errcode = 'P0002';
    end if;
  end if;

  update public.task_templates
  set
    title = btrim(p_title),
    description = nullif(btrim(p_description), ''),
    priority = p_priority,
    assigned_employee_id = p_assigned_employee_id,
    assignee = assignee_name,
    recurrence_type = p_recurrence_type,
    recurrence_interval = p_recurrence_interval,
    anchor_due_date = p_anchor_due_date
  where id = template_row.id
  returning * into template_row;

  select task.*
  into task_row
  from public.object_tasks task
  where task.task_template_id = template_row.id
    and task.status <> 'Виконано'
  order by task.recurrence_sequence desc, task.id desc
  limit 1
  for update;

  if template_row.is_active and task_row.id is not null then
    recalculated_due_date := private.task_recurrence_due_date(
      template_row.anchor_due_date,
      template_row.recurrence_type,
      template_row.recurrence_interval,
      task_row.recurrence_sequence
    );

    perform pg_catalog.set_config(
      'vicourt.recurring_task_mutation',
      'on',
      true
    );

    update public.object_tasks
    set
      title = template_row.title,
      description = template_row.description,
      due_date = recalculated_due_date,
      assignee = template_row.assignee,
      assigned_employee_id = template_row.assigned_employee_id,
      priority = template_row.priority
    where id = task_row.id
    returning * into task_row;
  end if;

  return jsonb_build_object(
    'template', to_jsonb(template_row),
    'first_task', case when task_row.id is null then null else to_jsonb(task_row) end,
    'reused_existing_series', false
  );
end
$function$;

create or replace function public.activate_task_template_series(
  p_template_id bigint,
  p_target_type text,
  p_object_id bigint,
  p_equipment_id bigint,
  p_anchor_due_date date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  source_row public.task_templates%rowtype;
  series_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
  first_slot record;
  reused boolean := false;
  today date := (clock_timestamp() at time zone 'Europe/Kyiv')::date;
begin
  perform private.assert_task_template_management();

  select template.*
  into source_row
  from public.task_templates template
  where template.id = p_template_id
  for update;

  if not found then
    raise exception 'Task template was not found.'
      using errcode = 'P0002';
  end if;

  if source_row.is_active
    or source_row.object_id is not null
    or source_row.equipment_id is not null
    or source_row.recurrence_type = 'none'
    or p_anchor_due_date is null
    or p_target_type not in ('object', 'equipment')
    or (p_target_type = 'object' and (p_object_id is null or p_equipment_id is not null))
    or (p_target_type = 'equipment' and (p_equipment_id is null or p_object_id is not null))
  then
    raise exception 'Only an unbound recurring blueprint can create a series.'
      using errcode = '22023';
  end if;

  if p_object_id is not null
    and not exists (
      select 1 from public.objects object where object.id = p_object_id
    )
  then
    raise exception 'Task target object was not found.'
      using errcode = 'P0002';
  end if;

  if p_equipment_id is not null
    and not exists (
      select 1 from public.equipment equipment where equipment.id = p_equipment_id
    )
  then
    raise exception 'Task target equipment was not found.'
      using errcode = 'P0002';
  end if;

  begin
    insert into public.task_templates (
      source_template_id,
      title,
      description,
      target_type,
      object_id,
      equipment_id,
      priority,
      assigned_employee_id,
      assignee,
      recurrence_type,
      recurrence_interval,
      anchor_due_date,
      is_active,
      created_by
    )
    values (
      source_row.id,
      source_row.title,
      source_row.description,
      p_target_type,
      p_object_id,
      p_equipment_id,
      source_row.priority,
      source_row.assigned_employee_id,
      source_row.assignee,
      source_row.recurrence_type,
      source_row.recurrence_interval,
      p_anchor_due_date,
      true,
      auth.uid()
    )
    returning * into series_row;
  exception
    when unique_violation then
      select template.*
      into series_row
      from public.task_templates template
      where template.source_template_id = source_row.id
        and template.is_active
        and template.target_type = p_target_type
        and template.object_id is not distinct from p_object_id
        and template.equipment_id is not distinct from p_equipment_id
      order by template.id
      limit 1
      for update;

      if not found then
        raise;
      end if;
      reused := true;
  end;

  if reused then
    select task.*
    into task_row
    from public.object_tasks task
    where task.task_template_id = series_row.id
      and task.status <> 'Виконано'
    order by task.recurrence_sequence desc, task.id desc
    limit 1;
  else
    select *
    into first_slot
    from private.next_task_recurrence_slot(
      series_row.anchor_due_date,
      series_row.recurrence_type,
      series_row.recurrence_interval,
      0,
      today - 1
    );

    task_row := private.create_task_template_occurrence(
      series_row.id,
      first_slot.recurrence_sequence,
      first_slot.due_date
    );
  end if;

  return jsonb_build_object(
    'template', to_jsonb(series_row),
    'first_task', case when task_row.id is null then null else to_jsonb(task_row) end,
    'reused_existing_series', reused
  );
end
$function$;

create or replace function public.disable_task_template(
  p_template_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
  was_active boolean;
begin
  perform private.assert_task_template_management();

  select template.*
  into template_row
  from public.task_templates template
  where template.id = p_template_id
  for update;

  if not found then
    raise exception 'Task template was not found.'
      using errcode = 'P0002';
  end if;

  was_active := template_row.is_active;

  if was_active then
    update public.task_templates
    set is_active = false
    where id = template_row.id
    returning * into template_row;
  end if;

  select task.*
  into task_row
  from public.object_tasks task
  where task.task_template_id = template_row.id
    and task.status <> 'Виконано'
  order by task.recurrence_sequence desc, task.id desc
  limit 1
  for update;

  -- Disabling is the explicit series action that releases the unfinished
  -- occurrence. It remains an ordinary manual task and therefore can still be
  -- completed or deleted through the pre-existing manual-task workflows.
  if task_row.id is not null then
    perform pg_catalog.set_config(
      'vicourt.recurring_task_mutation',
      'on',
      true
    );

    update public.object_tasks
    set
      task_template_id = null,
      recurrence_sequence = null
    where id = task_row.id
    returning * into task_row;
  end if;

  return jsonb_build_object(
    'template', to_jsonb(template_row),
    'first_task', case when task_row.id is null then null else to_jsonb(task_row) end,
    'reused_existing_series', not was_active
  );
end
$function$;

create or replace function public.create_manual_task_from_template(
  p_template_id bigint,
  p_target_type text,
  p_object_id bigint,
  p_equipment_id bigint,
  p_due_date date,
  p_assigned_employee_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.task_templates%rowtype;
  task_row public.object_tasks%rowtype;
  employee_id bigint;
  assignee_name text;
begin
  perform private.assert_task_template_management();

  select template.*
  into template_row
  from public.task_templates template
  where template.id = p_template_id
  for update;

  if not found then
    raise exception 'Task template was not found.'
      using errcode = 'P0002';
  end if;

  if template_row.recurrence_type <> 'none'
    or p_target_type not in ('object', 'equipment')
    or (p_target_type = 'object' and (p_object_id is null or p_equipment_id is not null))
    or (p_target_type = 'equipment' and (p_equipment_id is null or p_object_id is not null))
  then
    raise exception 'This template cannot create an ordinary manual task.'
      using errcode = '22023';
  end if;

  if p_object_id is not null
    and not exists (
      select 1 from public.objects object where object.id = p_object_id
    )
  then
    raise exception 'Task target object was not found.'
      using errcode = 'P0002';
  end if;

  if p_equipment_id is not null
    and not exists (
      select 1 from public.equipment equipment where equipment.id = p_equipment_id
    )
  then
    raise exception 'Task target equipment was not found.'
      using errcode = 'P0002';
  end if;

  employee_id := coalesce(
    p_assigned_employee_id,
    template_row.assigned_employee_id
  );
  if employee_id is not null then
    assignee_name := private.resolve_task_assignee_name(employee_id);
    if assignee_name is null then
      raise exception 'Assigned employee was not found.'
        using errcode = 'P0002';
    end if;
  end if;

  insert into public.object_tasks (
    object_id,
    equipment_id,
    title,
    description,
    due_date,
    assignee,
    assigned_employee_id,
    priority,
    status,
    task_source,
    task_template_id,
    recurrence_sequence
  )
  values (
    p_object_id,
    p_equipment_id,
    template_row.title,
    template_row.description,
    p_due_date,
    assignee_name,
    employee_id,
    template_row.priority,
    'Заплановано',
    'manual',
    null,
    null
  )
  returning * into task_row;

  return to_jsonb(task_row);
end
$function$;

create or replace function public.complete_manual_recurring_task(
  p_task_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  task_row public.object_tasks%rowtype;
  completed_row public.object_tasks%rowtype;
  next_task_row public.object_tasks%rowtype;
  template_row public.task_templates%rowtype;
  next_slot record;
  today date := (clock_timestamp() at time zone 'Europe/Kyiv')::date;
begin
  if auth.uid() is null or not private.is_active_user() then
    raise exception 'Only an active authenticated user can complete a task.'
      using errcode = '42501';
  end if;

  select task.*
  into task_row
  from public.object_tasks task
  where task.id = p_task_id;

  if not found then
    raise exception 'Task was not found.'
      using errcode = 'P0002';
  end if;

  if task_row.task_source <> 'manual'
    or task_row.task_template_id is null
    or task_row.recurrence_sequence is null
  then
    raise exception 'Task is not a manual recurring occurrence.'
      using errcode = '22023';
  end if;

  select template.*
  into template_row
  from public.task_templates template
  where template.id = task_row.task_template_id
  for update;

  if not found then
    raise exception 'Recurring task template was not found.'
      using errcode = 'P0002';
  end if;

  -- All series mutations lock template -> occurrence in the same order. This
  -- prevents a deadlock with concurrent template update/disable operations.
  select task.*
  into task_row
  from public.object_tasks task
  where task.id = p_task_id
  for update;

  if not found
    or task_row.task_source <> 'manual'
    or task_row.task_template_id is distinct from template_row.id
    or task_row.recurrence_sequence is null
  then
    raise exception 'Recurring task occurrence changed or no longer exists.'
      using errcode = '40001';
  end if;

  if task_row.status = 'Виконано' then
    select task.*
    into next_task_row
    from public.object_tasks task
    where task.task_template_id = task_row.task_template_id
      and task.recurrence_sequence > task_row.recurrence_sequence
      and task.status <> 'Виконано'
    order by task.recurrence_sequence, task.id
    limit 1;

    return jsonb_build_object(
      'already_completed', true,
      'template_id', template_row.id,
      'completed_task', to_jsonb(task_row),
      'next_task', case when next_task_row.id is null then null else to_jsonb(next_task_row) end
    );
  end if;

  if task_row.status not in ('Заплановано', 'В роботі') then
    raise exception 'Task is not in an active status.'
      using errcode = '22023';
  end if;

  perform pg_catalog.set_config(
    'vicourt.recurring_task_mutation',
    'on',
    true
  );

  update public.object_tasks
  set status = 'Виконано'
  where id = task_row.id
  returning * into completed_row;

  if template_row.is_active then
    select *
    into next_slot
    from private.next_task_recurrence_slot(
      template_row.anchor_due_date,
      template_row.recurrence_type,
      template_row.recurrence_interval,
      completed_row.recurrence_sequence,
      today
    );

    next_task_row := private.create_task_template_occurrence(
      template_row.id,
      next_slot.recurrence_sequence,
      next_slot.due_date
    );
  end if;

  return jsonb_build_object(
    'already_completed', false,
    'template_id', template_row.id,
    'completed_task', to_jsonb(completed_row),
    'next_task', case when next_task_row.id is null then null else to_jsonb(next_task_row) end
  );
end
$function$;

revoke all on function public.create_task_template(
  text,
  text,
  text,
  bigint,
  bigint,
  text,
  bigint,
  text,
  integer,
  date,
  boolean
) from public, anon;
grant execute on function public.create_task_template(
  text,
  text,
  text,
  bigint,
  bigint,
  text,
  bigint,
  text,
  integer,
  date,
  boolean
) to authenticated;

revoke all on function public.update_task_template(
  bigint,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  date
) from public, anon;
grant execute on function public.update_task_template(
  bigint,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  date
) to authenticated;

revoke all on function public.activate_task_template_series(
  bigint,
  text,
  bigint,
  bigint,
  date
) from public, anon;
grant execute on function public.activate_task_template_series(
  bigint,
  text,
  bigint,
  bigint,
  date
) to authenticated;

revoke all on function public.disable_task_template(bigint)
  from public, anon;
grant execute on function public.disable_task_template(bigint)
  to authenticated;

revoke all on function public.create_manual_task_from_template(
  bigint,
  text,
  bigint,
  bigint,
  date,
  bigint
) from public, anon;
grant execute on function public.create_manual_task_from_template(
  bigint,
  text,
  bigint,
  bigint,
  date,
  bigint
) to authenticated;

revoke all on function public.complete_manual_recurring_task(bigint)
  from public, anon;
grant execute on function public.complete_manual_recurring_task(bigint)
  to authenticated;

notify pgrst, 'reload schema';

commit;
